blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name


urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/<slug:slug>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {"blank": True, "null": True}


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.CharField(max_length=200, unique=True, verbose_name="Slug")
    content = models.TextField(verbose_name="Содержание", blank=True)
    preview_image = models.ImageField(
        upload_to="blog/preview", verbose_name="Изображение превью", **NULLABLE
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Признак публикации")
    views_count = models.PositiveIntegerField(
        default=0, verbose_name="Количество просмотров"
    )

    class Meta:
        verbose_name = "Пост в блоге"
        verbose_name_plural = "Посты в блоге"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

blog/forms.py
from django.forms import ModelForm
from mailing.forms import StyleFormMixin
from blog.models import BlogPost


class BlogPostForm(StyleFormMixin, ModelForm):
    class Meta:
        model = BlogPost
        fields = "__all__"

blog/views.py
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from blog.models import BlogPost
from blog.forms import BlogPostForm  # Импортируйте вашу форму


class BlogCreateView(CreateView):
    model = BlogPost
    form_class = BlogPostForm
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        blog = form.save(commit=False)
        if not blog.slug:
            base_slug = slugify(blog.title)
            slug = base_slug
            num = 1
            while BlogPost.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{num}"
                num += 1
            blog.slug = slug
        blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = BlogPost
    template_name = "blog/blogpost_list.html"  # Укажите ваш шаблон
    context_object_name = "blogpost_list"
    form_class = BlogPostForm  # Если используете форму
    extra_context = {"list_name": "Блог"}

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class BlogDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class BlogUpdateView(UpdateView):
    model = BlogPost
    form_class = BlogPostForm  # Используйте вашу форму

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", kwargs={"slug": self.object.slug})


class BlogDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Да</button>

                    </form>
                    <a href="{% url 'blog:blog_list' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card shadow-sm">

                        <div class="card-body">
                            <p class="card-text"><strong>{{ object.title }}</strong></p>
                            <p class="card-text">{{ object.content }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}"
                                       role="button">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'mailing/base.html' %}

{% block content %}
  <h2>{{ view.title }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row mt-4">
            <div class="col-12 text-center">
                <a class="btn btn-success btn-lg" href="{% url 'blog:blog_create' %}" role="button">Создать</a>
            </div>
        </div>
<div class="album py-5 bg-body-tertiary">

    <div class="container">
        <div class="row">
            {% for blog in blogpost_list %}
            <div class="col-6 mb-4">
                <div class="card shadow-sm">
                    <img src="{{ blog.photo | media_filter }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ blog.title }}</h5>
                        <p class="card-text">{{ blog.content | slice:":150" }}...</p>
                        <p class="card-text">Просмотров: {{ blog.views_count }}</p>
                        <p class="card-text">Дата публикации: {{ blog.created_at }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.slug %}" role="button">Посмотреть</a>
                            <a class="btn btn-warning" href="{% url 'blog:blog_edit' blog.slug %}" role="button">Редактировать</a>
                            <a class="btn btn-danger" href="{% url 'blog:blog_delete' blog.slug %}" role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}