blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name


urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/<slug:slug>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogDetailView
from .views import (
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    MailingListView,
    MailingDetailView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
    MailingAttemptListView,
    MailingAttemptDetailView,
    MailingAttemptCreateView,
    MailingAttemptUpdateView,
    MailingAttemptDeleteView,
    HomePageView,
    ContactView,
    RunMailingCommandView,
    RunMailingHardCommandView,
)


app_name = "mailing"


urlpatterns = [
    path("", cache_page(3)(HomePageView.as_view()), name="index"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("mailings/", MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailings/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path(
        "mailings/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path(
        "mailings/<int:mailing_id>/attempts/",
        MailingAttemptListView.as_view(),
        name="mailing_attempt_list",
    ),
    path(
        "mailings/<int:mailing_id>/attempts/<int:pk>/",
        MailingAttemptDetailView.as_view(),
        name="mailing_attempt_detail",
    ),
    path(
        "mailings/<int:mailing_id>/attempts/create/",
        MailingAttemptCreateView.as_view(),
        name="mailing_attempt_create",
    ),
    path(
        "mailings/<int:mailing_id>/attempts/<int:pk>/update/",
        MailingAttemptUpdateView.as_view(),
        name="mailing_attempt_update",
    ),
    path(
        "mailings/<int:mailing_id>/attempts/<int:pk>/delete/",
        MailingAttemptDeleteView.as_view(),
        name="mailing_attempt_delete",
    ),
    path("contacts/", ContactView.as_view(), name="contacts"),
    path(
        "mailings/<int:mailing_id>/run/",
        RunMailingCommandView.as_view(),
        name="run_mailing_command",
    ),
    path(
        "mailings/<int:mailing_id>/run/hard/",
        RunMailingHardCommandView.as_view(),
        name="run_mailing_hard_command",
    ),
]

users/urls.py
# from django.contrib.auth.views import LoginView, LogoutView
# from django.urls import path
# from users.apps import UsersConfig
# from users.views import UserCreateView, email_verification, password_reset_request
#
# app_name = UsersConfig.name
#
# urlpatterns = [
#     path("login/", LoginView.as_view(template_name="login.html"), name="login"),
#     path("logout/", LogoutView.as_view(), name="logout"),
#     path("register/", UserCreateView.as_view(), name="register"),
#     path(
#         "email-confirmation/<str:token>/", email_verification, name="email_confirmation"
#     ),
#     path("password-reset/", password_reset_request, name="password_reset"),
# ]


from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (UserCreateView, email_verification,
                        password_reset_request, ProfileView, ProfileUpdateView)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirmation/<str:token>/", email_verification, name="email_confirmation"),
    path("password-reset/", password_reset_request, name="password_reset"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = models.CharField(
        max_length=35,
        verbose_name="Телефон",
        **NULLABLE,
        help_text="Введите номер телефона"
    )
    country = models.CharField(
        max_length=150, verbose_name="Страна", help_text="Введите страну проживания"
    )
    avatar = models.ImageField(
        upload_to="users/avatars/", **NULLABLE, help_text="Загрузите свой аватар"
    )
    token = models.CharField(max_length=100, verbose_name="Token", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
# from django.contrib.auth.forms import UserCreationForm
# from django.forms import forms, EmailField
#
# from mailing.forms import StyleFormMixin
# from users.models import User
#
#
# class UserRegisterForm(StyleFormMixin, UserCreationForm):
#     class Meta:
#         model = User
#         fields = ("email", "password1", "password2")
#
#
# class PasswordResetForm(forms.Form):
#     email = EmailField(label="Email", max_length=254)


from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import EmailField

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class PasswordResetForm(forms.Form):
    email = EmailField(label="Email", max_length=254)


class UserProfileForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'country', 'avatar']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = False

users/views.py
# import secrets
# import random
# import string
# from django.contrib import messages
# from django.contrib.auth.hashers import make_password
# from django.core.mail import send_mail
# from django.shortcuts import render, get_object_or_404, redirect
# from django.urls import reverse_lazy, reverse
# from django.views.generic import CreateView
# from users.forms import UserRegisterForm, PasswordResetForm
# from users.models import User
# from config.settings import EMAIL_HOST_USER
#
#
# class UserCreateView(CreateView):
#     model = User
#     form_class = UserRegisterForm
#     success_url = reverse_lazy("users:login")
#
#     def form_valid(self, form):
#         user = form.save()
#         user.is_active = False
#         token = secrets.token_hex(16)
#         user.token = token
#         user.save()
#         host = self.request.get_host()
#         url = f"http://{host}/users/email-confirmation/{token}/"
#         try:
#             send_mail(
#                 subject="Подтверждение почты",
#                 message=f"Привет! , перейди по ссылке для подтверждения почты {url}",
#                 from_email=EMAIL_HOST_USER,
#                 recipient_list=[user.email],
#             )
#         except Exception as e:
#             user.delete()
#             messages.error(
#                 self.request, "Ошибка при отправке письма. Попробуйте еще раз."
#             )
#             return redirect("users:register")
#         return super().form_valid(form)
#
#
# def email_verification(request, token):
#     user = get_object_or_404(User, token=token)
#     user.is_active = True
#     user.token = None
#     user.save()
#     return redirect(reverse("users:login"))
#
#
# def generate_password(length=8):
#     characters = string.ascii_letters + string.digits
#     return "".join(random.choice(characters) for i in range(length))
#
#
# def password_reset_request(request):
#     if request.method == "POST":
#         form = PasswordResetForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data["email"]
#             try:
#                 user = User.objects.get(email=email)
#                 new_password = generate_password()
#                 user.password = make_password(new_password)
#                 user.save()
#                 try:
#                     send_mail(
#                         "Восстановление пароля",
#                         f"Ваш новый пароль: {new_password}",
#                         EMAIL_HOST_USER,
#                         [user.email],
#                         fail_silently=False,
#                     )
#                     messages.success(
#                         request, f"Новый пароль отправлен на почтовый ящик {user.email}"
#                     )
#                 except Exception as e:
#                     messages.error(
#                         request, "Ошибка при отправке письма. Попробуйте еще раз."
#                     )
#                 return redirect("users:login")
#             except User.DoesNotExist:
#                 messages.error(request, f"Пользователь с почтой {email} не существует")
#     else:
#         form = PasswordResetForm()
#     return render(request, "users/password_reset.html", {"form": form})



import secrets
import random
import string
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView
from users.forms import UserRegisterForm, PasswordResetForm, UserProfileForm
from users.models import User
from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirmation/{token}/"
        try:
            send_mail(
                subject="Подтверждение почты",
                message=f"Привет! , перейди по ссылке для подтверждения почты {url}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
        except Exception as e:
            user.delete()
            messages.error(
                self.request, "Ошибка при отправке письма. Попробуйте еще раз."
            )
            return redirect("users:register")
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.token = None
    user.save()
    return redirect(reverse("users:login"))


def generate_password(length=8):
    characters = string.ascii_letters + string.digits
    return "".join(random.choice(characters) for i in range(length))


def password_reset_request(request):
    if request.method == "POST":
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            try:
                user = User.objects.get(email=email)
                new_password = generate_password()
                user.password = make_password(new_password)
                user.save()
                try:
                    send_mail(
                        "Восстановление пароля",
                        f"Ваш новый пароль: {new_password}",
                        EMAIL_HOST_USER,
                        [user.email],
                        fail_silently=False,
                    )
                    messages.success(
                        request, f"Новый пароль отправлен на почтовый ящик {user.email}"
                    )
                except Exception as e:
                    messages.error(
                        request, "Ошибка при отправке письма. Попробуйте еще раз."
                    )
                return redirect("users:login")
            except User.DoesNotExist:
                messages.error(request, f"Пользователь с почтой {email} не существует")
    else:
        form = PasswordResetForm()
    return render(request, "users/password_reset.html", {"form": form})


class ProfileView(LoginRequiredMixin, DetailView):
    """Контроллер просмотра профиля пользователя"""
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'user_profile'

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования профиля пользователя"""
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile_edit.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Профиль успешно обновлен')
        return super().form_valid(form)

users/templates/users/password_reset.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Восстановить пароль</button>
                    <a class="btn btn-primary" href="{% url 'users:login' %}" role="button">Назад</a>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body text-center">
                    <img src="{{ user_profile.avatar.url }}" alt="Аватар" class="img-fluid rounded-circle mb-3" style="width: 150px; height: 150px; object-fit: cover;">
                    <h3>{{ user_profile.get_full_name }}</h3>
                    <p class="text-muted">{{ user_profile.email }}</p>
                    <a href="{% url 'users:profile_edit' %}" class="btn btn-primary">Редактировать профиль</a>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Информация о профиле</h5>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ user_profile.email }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Телефон</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ user_profile.phone|default:"Не указан" }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Страна</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ user_profile.country|default:"Не указана" }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>Редактирование профиля</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a href="{% url 'users:profile' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                        <a class="btn btn-primary" href="{% url 'mailing:index' %}" role="button">Назад</a>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}